from __future__ import annotations

from typing import Callable, Protocol


class TrafficAnalysisGateway(Protocol):
    def initialize(self) -> None: ...
    def corrected_traffic(self, request: dict) -> dict: ...
    def corrected_traffic_acsr(self, request) -> dict: ...
    def corrected_traffic_crsrd(self, request) -> dict: ...
    def corrected_traffic_drct(self, request) -> dict: ...
    def corrected_traffic_vknd(self, request) -> dict: ...
    def anomaly_daily_summary(self, request) -> dict: ...
    def run_job(self, job: dict) -> None: ...


class ReferenceDataGateway(Protocol):
    def intersections(self) -> list[dict]: ...
    def vehicle_kinds(self) -> list[dict]: ...


class JobStore(Protocol):
    def create(self, job: dict) -> None: ...
    def get(self, job_id: str) -> dict | None: ...
    def update(self, job_id: str, changes: dict) -> None: ...


class BackgroundJobRunner(Protocol):
    def submit(self, fn: Callable, *args) -> None: ...
    def shutdown(self) -> None: ...
